newton-physics/newton

- .github/workflows/pr.yml
- README.md
> Try out pre-commit integration

- .github/workflows/sphinx.yml
Fix an issue with deploying docs
> Fix omission in sphinx.yml

- newton/solvers/solver_mujoco.py
> Fix collision group warning #53

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .github/workflows/sphinx.yml
This PR enables the uploading of code coverage and unit test reports to https://app.codecov.io/gh/newton-physics/newton
GitHub actions have also been security-hardened by pinning them to specific commit SHA's.
Closes #62 
> Enable codecov.io

- .github/workflows/ci.yml
- .gitlab-ci.yml
Purpose is to ensure that users following instructions can run Newton tests on Windows.
> Add Windows testing to GitHub and GitLab workflows

- newton/utils/import_usd.py
Small fix to update the plane shape handling in the USD importer
> Fix plane shape parsing

- .pre-commit-config.yaml
- pyproject.toml
- uv.lock
Fix a Ruff warning due to a rule rename (?), update `uv.lock` file, update Ruff hooks.
> Update uv.lock, Ruff

- newton/core/builder.py
- newton/examples/assets/nv_ant.xml
- newton/examples/example_cartpole.py
- newton/solvers/solver_mujoco.py
- newton/tests/test_import_urdf.py
- newton/utils/import_mjcf.py
- newton/utils/import_urdf.py
- newton/utils/import_usd.py
- newton/utils/render.py
WIP fixing https://github.com/newton-physics/newton/issues/95
> Fix USD plane parsing, MuJoCoSolver, contact generation

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .github/workflows/sphinx.yml
This tries to fix some issues with doc building in GH workflows introduced by #122. Workflow updates of the UV version are also included.
> Update GitHub workflows

- docs/development-guide.rst
- pyproject.toml
- uv.lock
Add some more instructions on how to run doctest and build docs to the developer guide.
Update dependencies in `pyproject.toml`.
> Update docs and uv lockfile

- newton/utils/import_urdf.py
> Fix default handling in URDF importer

- newton/tests/test_mujoco_solver.py
Signed-off-by: Gordon Yeoman <gyeoman@nvidia.com>
> Refactor test framework  so we can more easily add custom configs.

- newton/solvers/mujoco/solver_mujoco.py
> Fix Mujoco axis regression

- newton/examples/example_anymal_c_walk_on_sand.py
- newton/solvers/implicit_mpm/solve_rheology.py
> Fix Anymal walk on sand example

- newton/examples/example_cloth_bending.py
- newton/examples/example_cloth_hanging.py
- newton/examples/example_cloth_self_contact.py
- newton/solvers/xpbd/kernels.py
- newton/tests/test_cloth.py
Fixed minor bending errors in XPBD. Unified function calls in cloth examples. Added more unit tests. #260
> Fixed minor bending errors in XPBD

- newton/sim/sew.py
> Remove warp.sim import

- newton/solvers/mujoco/solver_mujoco.py
- newton/tests/test_mujoco_solver.py
> Disable TestMuJoCoSolverGeomProperties

- newton/solvers/style3d/builder.py
- newton/solvers/style3d/kernels.py
- newton/solvers/style3d/solver_style3d.py
Accelerate PD matrix building ~20x via CPU Warp kernels.
> Accelerate matrix building

- newton/solvers/style3d/kernels.py
- newton/solvers/style3d/solver_style3d.py
During our development process, we identified a critical need for mouse-drag functionality, which is currently unsupported in the `Control` class. This is a preliminary implementation intended solely for development purposes.
> Add mouse-dragging support

- newton/utils/__init__.py
This was left over from previous debugging attempts.
> Fix `check_conditional_graph_support()` to return `True` on success

- .gitlab-ci.yml
> Update doctest runner to use R570

- .github/.dco.yml
- .github/workflows/pr_aws_gpu_tests.yml
- .github/workflows/push_aws_gpu_tests.yml
The previous settings are no longer sufficient to run the tests in the project.
Please ensure the migration guide for **warp.sim** users is up-to-date with the changes made in this PR.
> Increase timeout on AWS jobs
