newton-physics/newton

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr.yml, .github/workflows/sphinx.yml, .gitlab-ci.yml, docs/conf.py, docs/development-guide.rst, docs/quickstart.rst, uv.lock
This pull request enables `doctest` for Newton, including a job to test doctest snippets in the GitHub actions workflow (restricted to CPU only).
- A trivial example is added to the quickstart, which exercises this functionality.
- The Sphinx docs are changed to deploy on every push to main.
- The uv lockfile is also updated, which fixes an issue with the Windows wheel not being available for `warp-lang==1.8.0.dev20250507`.
- The pull request template is updated to remind authors that GitHub does not test the PR on GPUs
- `.gitlab-ci.yml` is updated to also run doctests
Closes #64 
=> Documentation updates

.github/workflows/ci.yml
Despite the codecov.io documentaiton, it seems that tokens are still required for actions running on protected branches like `main`.
=> Add `CODECOV_TOKEN` to coverage report step

pyproject.toml
The flake8 linter currently removes any quotation marks in type annotations. 
Sometimes those are necessary and removing them will result in a syntax error, for example when writing `Literal[a]` instead of `Literal["a"]`.
This PR ignores the corresponding warnings and disables the removal of these quotation marks.
=> Allow quotation marks in type annotations

newton/tests/test_import_usd.py, newton/utils/import_usd.py, newton/utils/topology.py
Makes breadth-first search the default in joint ordering when parsing articulations from USD.
Closes https://github.com/newton-physics/newton/issues/96.
=> Add option for BFS joint ordering to USD importer

.gitlab-ci.yml
On some Windows machines, there is a 32-bit version of Python set in the system path that will get used by uv sometimes. This pull request should fix that.
=> Don't use system Python on Windows CI runner (GitLab)

newton/examples/example_cartpole.py, newton/solvers/solver_mujoco.py
* Fixed an issue where the last shape of an articulation was not added to the mjModel when MJWarp is used (i.e. `separate_envs_to_worlds` is True)
* Use `disable_contacts=True` on the cartpole example
=> Fix skipping of shapes based on shapes_per_env variable

newton/examples/example_cloth_self_contact.py
Fixes #127.
Set better defaults for the open gl visualizer in example_cloth_self_contact.
Specifically default to:
- wireframe rendering (hard to see cloth deformation otherwise)
- no backface culling (sections of cloth otherwise disappear if we exit wireframe mode)
- no ground plane
Before:
After:
=> Improve opengl viz for example_cloth_self_contact

docs/development-guide.rst, docs/guide/overview.rst
Some links in the docs were using Markdown format inside a reST file, which doesn't work.
=> Fix some Markdown use in `.rst` files

newton/solvers/solver_mujoco.py, newton/tests/test_control_force.py
This fixes the test_control_force tests.
=> Ensure MuJoCoSolver can run on CPU

newton/core/inertia.py, newton/tests/assets/simple_articulation_with_mesh.usda, newton/tests/test_import_usd.py
When loading H1 (the version that can be found in IsaacLab's Nucleus folder) the method `_update_body_mass` is failing with the following error message:
```
File "/home/antoiner/Documents/newton/newton/utils/import_usd.py", line 854, in parse_usd
shape_id = builder.add_shape_mesh(
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/antoiner/Documents/newton/newton/core/builder.py", line 2124, in add_shape_mesh
return self.add_shape(
^^^^^^^^^^^^^^^
File "/home/antoiner/Documents/newton/newton/core/builder.py", line 1824, in add_shape
self._update_body_mass(body, m, I, com_body, xform.q)
File "/home/antoiner/Documents/newton/newton/core/builder.py", line 3101, in _update_body_mass
new_com = (self.body_com[i] * self.body_mass[i] + p * m) / new_mass
~~^~~
File …
```
=> Potential Fix when loading H1 from USD

docs/conventions.rst, docs/migration.rst, newton/core/builder.py, newton/core/model.py, newton/examples/__init__.py, newton/examples/assets/nv_humanoid.xml, newton/examples/example_cartpole.py, newton/examples/example_humanoid.py, newton/examples/example_quadruped.py, newton/tests/test_collision.py, newton/tests/test_up_axis.py
=> Set default up axis to Z

newton/utils/import_mjcf.py
The G1 asset in the assets repo uses contype and conaffinity to encode that a geom is visual. This is a bit of a hack but moves geoms that don't collide with anything to the visual class.
We should follow up and actually implement proper support for contype and conaffinity as currently these things have no effect and we overwrite it once again when assembling the mujoco model.
=> MJCF Parsing: move geoms with contype == 0 and conaffinity == 0 to visual geoms

newton/solvers/mujoco/solver_mujoco.py
This avoids generating very large convex meshes - improves performance quite a bit on G1/H1.
=> add maxHullVert parameter to MuJoCo solver

newton/sim/builder.py
I've further optimized Builder::add_cloth_grid() for enhanced performance, through:
1.  Fix duplicate vertex transform intrudced in last my [PR#178](https://github.com/newton-physics/newton/pull/178)
2.  Accelerate vertex transforms with NumPy vectorization
Performance improvements:
| Grid Size | Before  | After | Speedup |
|----------------------------------------|
|  200x200  |  14.6 sec.  |  1.0 sec.  |   ~x15   |
=> Accelerate cloth grid generation

newton/examples/example_cloth_bending.py, newton/examples/example_robot_manipulating_cloth.py, newton/sim/builder.py, newton/sim/collide.py, newton/sim/model.py
* Fix soft collision handling (fixes cloth sim examples from VBD). Fixes #215.
* Move rigid contact point counting to `ModelBuilder.finalize()` so that `Model.collide()` becomes graph-captureable. Fixes #234.
=> Fix soft contact handling, make `Model.collide()` graph-captureable

newton/solvers/mujoco/solver_mujoco.py
mujoco_warp `model.opt.timestep` is a Warp array now, so we have to `array.fill_(dt)`
=> Fix mujoco_warp model.opt.timestep update

newton/examples/example_cloth_self_contact.py, newton/examples/example_robot_manipulating_cloth.py, newton/solvers/vbd/solver_vbd.py, newton/tests/test_cloth.py
Renamed the `soft_contact_margin` in `VBDSolver` to `self_contact_margin` to differentiate from the parameter that controls particle-contact in `collide`.
Fix a bug where the default soft-contact margin is used for particle-body contact detection in the robot manipulation demo.
=> Fix the Incorrect `soft_contact_margin` used in the Robot-Cloth Manipulation Demo

newton/sim/builder.py, newton/sim/graph_coloring.py, newton/tests/test_coloring.py, pyproject.toml, uv.lock
This change bumps up the `uv.lock` file to use new versions...including Warp nightly, which has some changes regarding adding the `wp_` prefix to various functions.
Everyone using Newton after this pull request is merged will need to be on the nightly that this one uses (or newer).
```
Warp 1.8.0.dev20250625 initialized:
Git commit: d3639b92807e402c0c33ee65516973066621f143
CUDA Toolkit 12.8, Driver 12.4
Devices:
"cpu"      : "x86_64"
"cuda:0"   : "NVIDIA A40" (47 GiB, sm_86, mempool enabled)
Kernel cache:
/home/horde/.cache/warp/1.8.0.dev20250625
```
=> Update Warp + Namespacing updates

newton/tests/test_import_usd.py, newton/utils/import_usd.py
=> USD importer density fix

newton/examples/example_selection_articulations.py, newton/examples/example_selection_cartpole.py, newton/sim/model.py, newton/utils/isaaclab.py, newton/utils/selection.py
This PR supersedes the first PR (https://github.com/newton-physics/newton/pull/119).
The attribute API is similar to the previous version, e.g.:
```python
joint_transforms = view.get_attribute("joint_q", state)
joint_velocities = view.get_attribute("joint_qd", state)
...
view.set_attribute("joint_q", state, joint_transforms)
view.set_attribute("joint_qd", state, joint_velocities)
```
This is a flexible approach that makes it easy to incorporate custom attributes by name without the need to add new API entry points.
By default, the attribute API always includes all joints, links, and DOFs. This allows users familiar with the Newton model to work efficiently with the underlying data.
We now allow filtering joints and links to give users more control over articulation views, e.g.:
```python …
```
=> Selection API v2

newton/tests/test_cloth.py
Whenever graph capture is involved, we need to be careful about making sure the modules are preloaded since they cannot be dynamically loaded when the CUDA driver is older than 12.3.
=> Fix issues with `test_cloth.py` on CUDA drivers < 12.3

newton/sim/graph_coloring.py
I hope to address two issues with this common warning that appears in the cloth examples:
- It's not clear what this warning is talking about. What graph?
- The number of digits printed out is absurdly long and don't tell the user much (now limited to three after the decimal point)
Current:
```
Warp UserWarning: The graph is not optimizable anymore, terminated with a max/min ratio: 1.3333333730697632 without reaching the target ratio: 1.1
```
This pull request:
```
Warp UserWarning: Color balancing terminated early: max/min ratio 1.333 exceeds target 1.100. The graph may not be further optimizable.
```
=> Refactor warning message in `color_graph` function for clarity

newton/geometry/__init__.py, newton/geometry/types.py, newton/geometry/utils.py, newton/solvers/mujoco/solver_mujoco.py, newton/tests/test_import_mjcf.py, newton/tests/test_mujoco_solver.py, newton/utils/import_mjcf.py
This PR addresses issue #222 by implementing support for per-mesh `maxhullvert` configuration and pre-computed convex hulls in the MuJoCo solver.
- **Added `maxhullvert` attribute to `Mesh` class**: Meshes can now specify their maximum convex hull vertex count (default: 64)
- **Added `convex_hull` support**: Meshes can store pre-computed convex hulls to avoid redundant computation in MuJoCo
- **Updated MJCF importer**: Now parses the `maxhullvert` attribute from MJCF mesh elements
- **Enhanced MuJoCo solver**: 
- Uses per-mesh `maxhullvert` values instead of the hardcoded default
- Utilizes pre-computed convex hulls when available, falling back to MuJoCo's auto-computation
- **Flexibility**: Users can control convex hull complexity per mesh
- **Performance**: Pre-computed convex hulls …
=> Add per-mesh maxhullvert support and pre-computed convex hull capability (#222)

newton/tests/test_rigid_contact.py
I noticed when testing on a multi-GPU system that all these tests fail on the second GPU. It seems that the `wp.ScopedCapture()` was not targeting the intended device.
=> Ensure `wp.ScopedCapture()` happens on the right device

newton/solvers/mujoco/solver_mujoco.py, newton/tests/test_mujoco_solver.py
This PR improves the MuJoCo solver's shape-to-geom mapping efficiency and correctness. Closes #330.
**Key improvements:**
1. **Fixed geom index mapping** - The solver now queries actual geom indices from MuJoCo after model compilation using `mj_name2id`, ensuring correct mapping even if MuJoCo reorders geoms internally.
2. **Improved `update_geom_properties_kernel` efficiency** - Rewrote the kernel to launch one thread per geom instead of per shape:
- Removed inefficient `selected_shapes` indirection
- Uses `to_newton_shape_index` array for reverse mapping (geom → shape)
- Launches with `(num_worlds, num_geoms)` dimensions for better parallelization
- Only processes geoms that actually exist in MuJoCo
3. **Removed duplicate mapping data** - Eliminated redundant `shape_to_geom` array that …
=> Fix MuJoCo solver shape-to-geom mapping and improve update efficiency

.github/workflows/ci.yml, .gitlab-ci.yml, docs/development-guide.rst, newton/examples/example_anymal_c_walk.py, newton/examples/example_anymal_c_walk_on_sand.py, newton/tests/test_examples.py, pyproject.toml, uv.lock
- Add a PyTorch dependency. This can be installed by running `uv run --extra cu128 name_of_script.py`
- Test the Anymal examples (GPU testing only due to how the examples were written)
- Early-out if the Anymal examples is run on the CPU
- Apply fix from #318 to the sand example
- Clean up uv dependency group usage
- Mass-update of dependencies in the `uv.lock` file
- Update documentation to avoid `--all-extras` (too heavy-handed, especially with the PyTorch extra)
=> Add PyTorch to `--extra cu12`, fix Anymal Sand example

pyproject.toml, uv.lock
Add asv to uv development dependency
Use a more recent version of the Warp nightly.
At some point, `mujoco-warp` changed their version number from 3.2.7 (mirroring mujoco) to 0.0.1, which can cause trouble with the way our `pyproject.toml` is configured.
=> Update Warp dependency, lower minimum `mujoco-warp` version

newton/examples/example_anymal_c_walk.py, newton/examples/example_anymal_c_walk_on_sand.py, newton/examples/example_cartpole.py, newton/examples/example_cloth_bending.py, newton/examples/example_cloth_hanging.py, newton/examples/example_cloth_self_contact.py, newton/examples/example_cloth_style3d.py, newton/examples/example_g1.py, newton/examples/example_humanoid.py, newton/examples/example_mpm_granular.py, newton/examples/example_quadruped.py, newton/examples/example_robot_manipulating_cloth.py, newton/examples/example_selection_articulations.py, newton/examples/example_selection_cartpole.py, newton/examples/example_selection_materials.py, newton/tests/test_examples.py
This aligns us with the norm for argparse-based command line parameters.
Some examples were cleaned up as well, e.g. consistency with the `__init__()` defaults and argparse defaults.
=> Rename example argument names to use hyphens instead of underscores

newton/examples/example_rigid_force.py, newton/examples/example_robot_manipulating_cloth.py, newton/examples/example_selection_articulations.py, newton/examples/example_selection_cartpole.py, newton/examples/example_selection_materials.py, newton/tests/test_examples.py
- Add testing of `example_rigid_force.py` and update conventions
- Revert disabling of conditional nodes in `newton/examples/example_selection_articulations.py`
- Clean up `test_examples.py` runner
- Clean up examples to consistently set a default `stage_path` in the `Example` class constructor
=> Minor updates to examples and testing

.coderabbit.yml, .github/workflows/release.yml
CodeQL says:
> If a GitHub Actions job or workflow has no explicit permissions set, then the repository permissions are used. Repositories created under organizations inherit the organization permissions. The organizations or repositories created before February 2023 have the default permissions set to read-write. Often these permissions do not adhere to the principle of least privilege and can be reduced to read-only, leaving the write permission only to a specific types as issues: write or pull-requests: write.
=> Fix a CodeQL warning about permissions in release workflow
